### ISSUE TITLE
Fix API mocking in verify function tests

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/identity-service#125]
A test-running setup for identity service is added (refer to these: https://github.com/Real-Dev-Squad/identity-service/pull/109, https://github.com/Real-Dev-Squad/identity-service/pull/108).

We also added the API mocking in verification function tests but they are not working as expected.

**Comment by ruthv1k** [comment]
Hey @lakshayman, I'm interesting in working on this.
