### ISSUE TITLE
[RFC] Where to store identityURL?

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/identity-service#20]
We are creating an Identity Service (backend service using golang) through which we are going to make requests on each user's identityURL endpoints, created by users, to get the Identity (Profile Data eg. Name, LinkedinUrl, GitHub username, etc) of the user. We have a user object for each user, in users collection in firestore which stores the identity/Profile data of the user.

So the question is where should we store the identityURL?
- In the user object
- In the different collection, storing username with identityURL

In my opinion, identityURL belongs to the user so it should be stored in user object in users collection.
Will it cause any problems in the future?

What do you guys think?

**Comment by MehulKChaudhari** [comment]
I think we should store identityUrl in the user collection. We don't need a whole new collection for one field and that too is directly related to the user and is part of the user's information so I think we should store it in the user collection.

**Comment by rohan09-raj** [comment]
The user object is the better place to store the identity URL.
Collections are used if we have any set of information which belongs to some kind.
So here, identity URL is not any different set of information, it is only a single piece of information that belongs to the user only.

**Comment by lakshayman** [comment]
Considering the comments
Lets store them in user's object
