### ISSUE TITLE
Necessary Firestore Indexes.

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/identity-service#64]
# 1
## CollectionId
chaincodes

## Fields indexed
userId Ascending
timestamp Descending

# 2
## CollectionId
profileDiffs

## Fields indexed
approval Ascending
userId Ascending
timestamp Descending

**Comment by ankushdharkar** [comment]
Thank you! Done ✅

**Comment by vinayak-trivedi** [comment]
### collection 
tasks

### fields
- assignee | Ascending 
- id | Ascending

- status | Ascending 
- taskLevel.category |  Ascending 
- taskLevel.level |  Ascending
