### ISSUE TITLE
Identity Service Release

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/identity-service#67]
# PR's to be merged before release:
## APPROVED
Backend: 
https://github.com/Real-Dev-Squad/website-backend/pull/526

My-Site:
https://github.com/Real-Dev-Squad/website-my/pull/224

Dashboard Site:
https://github.com/Real-Dev-Squad/website-dashboard/pull/142

## Pending for Re-review:
Backend:
https://github.com/Real-Dev-Squad/website-backend/pull/525
https://github.com/Real-Dev-Squad/website-backend/pull/554

## Pending for Review:
Backend:
https://github.com/Real-Dev-Squad/website-backend/pull/555
https://github.com/Real-Dev-Squad/website-backend/pull/547

- [x] Necessary Firestore Indexes
https://github.com/Real-Dev-Squad/identity-service/issues/64

- [x] Put the Firestore Credentials in Package Manager SSM with the name `firestoreCred`.

- [x] Give the roles, we are using in Lambda function, SSM access.

- [x] Set the environment variable named `IDENTITY_SERVICE_URL` in Heroku to the identity service URL.

**Comment by ankushdharkar** [comment]
All steps are completed. Thank you for creating this ticket!
