### ISSUE TITLE
Change the way we block a service and accessing the chaincode

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/identity-service#78]
- [ ] Currently, to block a service, we are generating a new chaincode. So that previous one expires. This is because we are fetching the latest chaincode so if we generate a new one, the previous one automatically expires. But now we are bringing the chaincode from the user's object. So if you want to block the chaincode set the `chaincode` key to `""` in the user's object.
- [ ] Currently, we are accessing chaincode by fetching the latest from the chaincodes collection, change it to fetch from the chaincode key in the user's object.

**Comment by akash2819** [comment]
Please assign it to me !!

**Comment by akash2819** [comment]
@lakshayman  can you please reassign it to me I accidentally unassigned it ?

**Comment by Maheima** [comment]
I want to take it up
