### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/identity-service#86]
- [x] Make the log type names a bit sensible.
- [x] Add Identity Service Sequence diagram in readme. 
#88
![Profile Service Sequence Diagram (1)](https://user-images.githubusercontent.com/45519620/176491640-6f58d7d5-6fe1-42d9-a9d6-fc1b23e0dee2.jpg)

**Comment by ojas-elawadhi** [comment]
assign me
